# Generated by Django 2.2.3 on 2020-11-29 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='COVID_19',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=8, verbose_name='UserName')),
                ('ScreenName', models.CharField(max_length=10, verbose_name='ScreenName')),
                ('Location', models.CharField(blank=True, max_length=50, null=True, verbose_name='Location')),
                ('TweetAt', models.DateField(auto_now_add=True, verbose_name='TweetAt')),
                ('OriginalTweet', models.CharField(max_length=80000, verbose_name='OriginalTweet')),
                ('Sentiment', models.CharField(max_length=25, verbose_name='Sentiment (Neutral, Positive, Extremely Negative, Negative)')),
            ],
        ),
    ]
