# Generated by Django 2.2.3 on 2020-11-29 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Titulo', models.CharField(max_length=90, verbose_name='Titulo')),
                ('slug', models.CharField(max_length=100, verbose_name='slug')),
                ('descripcion', models.CharField(max_length=110, verbose_name='descripcion')),
                ('cotenido', models.TextField(verbose_name='contenido')),
                ('imagen', models.URLField(max_length=255)),
                ('estado', models.BooleanField(default=True, verbose_name='public/No-public')),
                ('fechaCre', models.DateField(auto_now_add=True, verbose_name='fechaCre')),
                ('COVID_19', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweets.COVID_19')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
