# Generated by Django 2.2.3 on 2020-12-01 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0005_post_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Titulo',
        ),
        migrations.AddField(
            model_name='post',
            name='titulo',
            field=models.CharField(default=5, max_length=90, verbose_name='Título'),
            preserve_default=False,
        ),
    ]
