# Generated by Django 2.2.3 on 2020-12-01 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0006_auto_20201130_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='covid_19',
            name='categoria',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='tweets.Categoria'),
            preserve_default=False,
        ),
    ]
