# Generated by Django 2.2.3 on 2020-12-01 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0007_covid_19_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='covid_19',
            name='categoria',
        ),
    ]
