# Generated by Django 2.2.3 on 2020-12-01 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0010_auto_20201201_0037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='covid_19',
            name='cat',
        ),
    ]
